# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d50c496bb00675cd691b489872432f7a82493fa9d7b3ce20f064278d1e3dd224bbb606dd72fa5434a14ec8dbff4a5c7cc98f791b97aebe2374ef97c2af566944

test:
  secret_key_base: c93979e087bb204da802f6ea3191d71835272be090bd785bd5a17ff46e300649a88f326aac888ce6335ac589a1e82c613a4339c692518a386d7453280c2babd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
